USE [vnc4]
GO
/****** Objet :  Table [dbo].[LOCK]    Date de génération du script : 07/15/2009 14:46:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOCK](
	[LCK_PERSISTID] [int] NOT NULL,
	[LCK_TYPE] [varchar](50) COLLATE French_CI_AS NOT NULL,
	[LCK_NAME] [varchar](50) COLLATE French_CI_AS NULL,
	[LCK_DATE] [datetime] NULL,
 CONSTRAINT [PK_LOCK] PRIMARY KEY CLUSTERED 
(
	[LCK_PERSISTID] ASC,
	[LCK_TYPE] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF

