GO

/****** Object:  View [dbo].[CA_MENSUELCLIENT_CODECLIENT]    Script Date: 27/02/2017 16:24:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[CA_MENSUELCLIENT_CODECLIENT]
AS
SELECT DISTINCT CLT_CODE
FROM            dbo.CA_MENSUELCLIENT

GO