USE [vnc5]
GO

/****** Object:  View [dbo].[CA_MENSUELPRODUCTEUR]    Script Date: 27/02/2017 17:07:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[CA_MENSUELPRODUCTEUR]
AS
SELECT        dbo.FOURNISSEUR.FRN_CODE, dbo.FOURNISSEUR.FRN_RS, dbo.FOURNISSEUR.FRN_NOM, MONTH(dbo.SOUSCOMMANDE.SCMD_DATE) AS mois, YEAR(dbo.SOUSCOMMANDE.SCMD_DATE) AS anne, 
                         SUM(dbo.LIGNE_COMMANDE.LGCM_PRIX_HT) AS CAHT, dbo.PRODUIT.PRD_CODE, dbo.PRODUIT.PRD_LIBELLE
FROM            dbo.SOUSCOMMANDE INNER JOIN
                         dbo.FOURNISSEUR ON dbo.SOUSCOMMANDE.SCMD_FRN_ID = dbo.FOURNISSEUR.FRN_ID INNER JOIN
                         dbo.LIGNE_COMMANDE ON dbo.SOUSCOMMANDE.SCMD_ID = dbo.LIGNE_COMMANDE.LGCM_SCMD_ID INNER JOIN
                         dbo.PRODUIT ON dbo.LIGNE_COMMANDE.LGCM_PRD_ID = dbo.PRODUIT.PRD_ID
WHERE        (YEAR(dbo.SOUSCOMMANDE.SCMD_DATE) >= YEAR(GETDATE()) - 3)
GROUP BY YEAR(dbo.SOUSCOMMANDE.SCMD_DATE), MONTH(dbo.SOUSCOMMANDE.SCMD_DATE), dbo.FOURNISSEUR.FRN_CODE, dbo.FOURNISSEUR.FRN_RS, dbo.SOUSCOMMANDE.SCMD_DATE, 
                         dbo.SOUSCOMMANDE.SCMD_TOTAL_HT, dbo.FOURNISSEUR.FRN_NOM, dbo.LIGNE_COMMANDE.LGCM_PRIX_HT, dbo.PRODUIT.PRD_CODE, dbo.PRODUIT.PRD_LIBELLE

GO
