
-- UPDATE SOUSCOMMANDE HOBIVIN 2017-2018
 UPDATE SOUSCOMMANDE 
 SET SCMD_COM_TAUX = 12, SCMD_COM_MONTANT = SCMD_COM_BASE * (0.12)
 WHERE SCMD_ID IN (
 SELECT         SCMD_ID
 FROM            SOUSCOMMANDE INNER JOIN
                         CLIENT ON SOUSCOMMANDE.SCMD_CLT_ID = CLIENT.CLT_ID
 WHERE        (CLIENT.CLT_CODE = N'003517') AND YEAR(SCMD_DATE)>=2017
 )
 GO
  update LIGNE_COMMANDE
SET LGCM_TXCOMM = SCMD_COM_TAUX , LGCM_MTCOMM = LGCM_PRIX_HT * SCMD_COM_TAUX/100
FROM LIGNE_COMMANDE inner join SOUSCOMMANDE on LGCM_SCMD_ID = SCMD_ID  inner join client on SCMD_CLT_ID = clt_id
where clt_code = '003517' and year(SCMD_DATE)>=2017
GO

update LIGNE_COMMANDE
SET LGCM_TXCOMM = 9.5 , LGCM_MTCOMM = LGCM_PRIX_HT * 0.095
FROM LIGNE_COMMANDE inner join SOUSCOMMANDE on LGCM_SCMD_ID = SCMD_ID  inner join client on SCMD_CLT_ID = clt_id
inner join FOURNISSEUR on SCMD_FRN_ID = frn_id
where clt_code = '003517' and year(SCMD_DATE)>=2017 and frn_code = '052'

update SousCOMMANDE
SET SCMD_COM_TAUX = 9.5 , SCMD_COM_MONTANT = SCMD_COM_BASE * 0.095
FROM SOUSCOMMANDE 
inner join client on SCMD_CLT_ID = clt_id
inner join FOURNISSEUR on SCMD_FRN_ID = frn_id
where clt_code = '003517' and year(SCMD_DATE)>=2017 and frn_code = '052'