--Ajout de clé Etrangères sur Precommandes
ALTER TABLE [dbo].[PRECOMMANDE]  WITH CHECK ADD  CONSTRAINT [FK_PRECOMMANDE_CLIENT] FOREIGN KEY([PCMD_CLT_ID])
REFERENCES [dbo].[CLIENT] ([CLT_ID]);
GO

ALTER TABLE [dbo].[PRECOMMANDE]  WITH CHECK ADD  CONSTRAINT [FK_PRECOMMANDE_PRODUIT] FOREIGN KEY([PCMD_PRD_ID])
REFERENCES [dbo].[PRODUIT] ([PRD_ID])
GO


-- Ajout de la notion de Dossier
ALTER TABLE dbo.PRODUIT ADD
	PRD_DOSSIER nvarchar(50) NULL;
GO
UPDATE PRODUIT SET PRD_DOSSIER = 'VINICOM';
GO
UPDATE PRODUIT SET PRD_DOSSIER = 'HOBIVIN' WHERE PRD_FRN_ID in (SELECT FRN_ID FROM FOURNISSEUR WHERE FRN_BEXP_INTERNET = '2');
GO

ALTER TABLE [dbo].[LIGNE_COMMANDE] DROP CONSTRAINT [FK_LIGNE_COMMANDE_COMMANDE]
GO
ALTER TABLE [dbo].[LIGNE_COMMANDE]  WITH NOCHECK ADD  CONSTRAINT [FK_LIGNE_COMMANDE_COMMANDE] FOREIGN KEY([LGCM_CMD_ID])
REFERENCES [dbo].[COMMANDE] ([CMD_ID])
NOT FOR REPLICATION 
GO

-- TEST UNITAIRES
ALTER TABLE [dbo].[LIGNE_COMMANDE] NOCHECK CONSTRAINT [FK_LIGNE_COMMANDE_COMMANDE]
GO

-- TX COMMISSION
insert into FRN_COMM (FRNC_FRN_ID, FRNC_TYPE_CLIENT, FRNC_TX_COMM) 
SELECT  FRN_ID, 'INT', 12.0 from FOURNISSEUR


--Numéro de version
UPDATE CONSTANTES SET CST_VERSION_BD='5.9.3';