DELETE FROM EXPORTPARAM where EXP_TYPE in ('QFACT') AND EXP_NLIGNE = 1 AND EXP_NCHAMPS >= 14
GO
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 14, 'C', ';', 0, '')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 15, 'V', 'CODEDEPOT', 0, 'Code Dépot')
GO
