DELETE FROM EXPORTPARAM where EXP_TYPE in ('QFACT')
GO
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 1, 'V', 'Identifiant', 0, 'Code client / Fournisseur')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 2, 'C', ';', 0, ';')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 3, 'V', 'Reference1', 0, 'Code Commande')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 4, 'C', ';', 0, ';')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 5, 'V', 'DatePiece', 0, 'Date Commande')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 6, 'C', ';', 0, ';')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 7, 'V', 'PieceRegroup', 0, 'Code Commande')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 8, 'C', ';', 0, ';')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 9, 'V', 'CodeARTICLE', 0, 'Code Article')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 10, 'C', ';', 0, ';')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 11, 'V', 'Quantite', 0, 'Qte')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 12, 'C', ';', 0, ';')
INSERT [dbo].[EXPORTPARAM] ([EXP_TYPE], [EXP_NLIGNE], [EXP_NCHAMPS], [EXP_TYPECHAMPS], [EXP_VALEUR], [EXP_LONGUEUR], [EXP_DESCRIPTION]) VALUES ('QFACT', 1, 13, 'V', 'PrixHT', 0, 'Prix Unitaire')


--Numéro de version
UPDATE CONSTANTES SET CST_VERSION_BD='5.9.1';