
ALTER TABLE dbo.COMMANDE ADD
	CMD_CLT_NOM nvarchar(50) NULL
GO
GO
ALTER TABLE dbo.COMMANDE ADD
	CMD_CLT_RS nvarchar(50) NULL
GO
GO
ALTER TABLE dbo.BONAPPRO ADD
	CMD_CLT_NOM nvarchar(50) NULL
GO
GO
ALTER TABLE dbo.BONAPPRO ADD
	CMD_CLT_RS nvarchar(50) NULL
GO
ALTER TABLE dbo.CONSTANTES ADD
	CST_EDI_HOST nvarchar(50) NULL
GO
ALTER TABLE dbo.CONSTANTES ADD
	CST_EDI_PORT nvarchar(50) NULL
GO
ALTER TABLE dbo.CONSTANTES ADD
	CST_EDI_FROM nvarchar(50) NULL
GO
ALTER TABLE dbo.CONSTANTES ADD
	CST_EDI_TEMP nvarchar(50) NULL
GO
ALTER TABLE dbo.CONSTANTES ADD
	CST_SRVCE_PATH nvarchar(100) NULL
GO
ALTER TABLE dbo.CONSTANTES ADD
	CST_SRVCE_NBSEC varchar(10) NULL
GO
ALTER TABLE dbo.CONSTANTES ADD
	CST_SRVCE_PATHERROR nvarchar(100) NULL
GO
UPDATE CONSTANTES SET CST_VERSION_BD = '5.0'
GO
DELETE FROM EXPORTPARAM WHERE EXP_TYPE = 'CMDCLT'
GO
insert into EXPORTPARAM(EXP_TYPE,EXP_NLIGNE,EXP_NCHAMPS,EXP_TYPECHAMPS,EXP_VALEUR,EXP_LONGUEUR,EXP_DESCRIPTION) VALUES
('CMDCLT',1,1,'V','CMD_TIERS_CODE',0,'Code Client'),
('CMDCLT',1,2,'V','CMD_DATECOMMANDE',0,'Date commande'),
('CMDCLT',1,3,'V','LGCMD_PRD_CODE',0,'Code Produit'),
('CMDCLT',1,4,'V','LGCMD_QTECOM',0,'Qte Commandée'),
('CMDCLT',1,5,'V','LGCMD_PU',0,'Prix Unitaire'),
('CMDCLT',1,6,'V','CMD_COM_COM',0,'Commentaire commande')
GO
DELETE FROM USERSRIGHTS
GO
insert into USERSRIGHTS (RGH_TAG,RGH_ROLE,RGH_DROIT,RGH_TEXT) VALUES
('mnuScmd',3,0,'SousCommandes'),
('MnuTrp',3,0,'Transport'),
('MnuCol',3,0,'Colisage'),
('mnuCompta',3,0,'Comptabilité'),
('MNUUTIL',3,0,'Utilitaires')

GO
CREATE TABLE [dbo].[MENUS](
	[MNU_TAG] [varchar](50) NULL,
	[MNU_TEXT] [varchar](50) NULL
) ON [PRIMARY]
