USE [vnc5]
GO

/****** Object:  Table [dbo].[FACTHBV]    Script Date: 20/03/2017 15:43:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACTHBV](
	[FHBV_ID] [int] IDENTITY(1,1) NOT NULL,
	[FHBV_CODE] [nvarchar](50) NOT NULL,
	[FHBV_DATE] [datetime] NULL,
	[FHBV_CLT_ID] [int] NULL,
	[FHBV_TOTAL_TAXES] [float] NULL,
	[FHBV_TOTAL_HT] [float] NULL,
	[FHBV_TOTAL_TTC] [float] NULL,
	[FHBV_ETAT] [int] NULL,
	[FHBV_MONTANT_REGLEMENT] [float] NULL,
	[FHBV_DATE_REGLEMENT] [datetime] NULL,
	[FHBV_REF_REGLEMENT] [nvarchar](50) NULL,
	[FHBV_COM_FACT] [nvarchar](50) NULL,
	[FHBV_IDMODEREGLEMENT] [int] NULL,
	[FHBV_DECHEANCE] [datetime] NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[FACTHBV] ADD  CONSTRAINT [DF_FACTTRP_FHBV_BINTERNET]  DEFAULT ((0)) FOR [FHBV_BINTERNET]
GO

ALTER TABLE COMMANDE
	ADD CMD_IDFHBV int null
GO
ALTER TABLE COMMANDE
	ADD CMD_ORIGINE nvarchar(10)
GO


UPDATE CONSTANTES SET CST_VERSION_BD = '5.9'
GO
