USE [vnc5]
GO

/****** Object:  Table [dbo].[FACTHBV]    Script Date: 20/03/2017 15:43:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACTHBV](
	[FHBV_ID] [int] IDENTITY(1,1) NOT NULL,
	[FHBV_CODE] [nvarchar](50) NOT NULL,
	[FHBV_DATE] [datetime] NULL,
	[FHBV_CLT_ID] [int] NULL,
	[FHBV_TOTAL_TAXES] [float] NULL,
	[FHBV_TOTAL_HT] [float] NULL,
	[FHBV_TOTAL_TTC] [float] NULL,
	[FHBV_ETAT] [int] NULL,
	[FHBV_MONTANT_REGLEMENT] [float] NULL,
	[FHBV_DATE_REGLEMENT] [datetime] NULL,
	[FHBV_REF_REGLEMENT] [nvarchar](50) NULL,
	[FHBV_COM_FACT] [nvarchar](50) NULL,
	[FHBV_IDMODEREGLEMENT] [int] NULL,
	[FHBV_DECHEANCE] [datetime] NULL,
	[FHBV_IDCOMMANDE] [int] NULL,
) ON [PRIMARY]
GO
ALTER TABLE dbo.FACTHBV ADD CONSTRAINT
	PK_FACTHBV PRIMARY KEY CLUSTERED 
	(
	FHBV_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO


CREATE TABLE [dbo].[LIGNE_FACTHBV](
	[LGFHBV_ID] [int] IDENTITY(1,1) NOT NULL,
	[LGFHBV_FACT_ID] [int] NULL,
	[LGFHBV_PRD_ID] [int] NULL,
	[LGFHBV_QTE_COMMANDE] [int] NULL DEFAULT ((0)),
	[LGFHBV_QTE_LIV] [int] NULL DEFAULT ((0)),
	[LGFHBV_QTE_FACT] [int] NULL DEFAULT ((0)),
	[LGFHBV_PRIX_UNITAIRE] [money] NULL DEFAULT ((0)),
	[LGFHBV_PRIX_HT] [money] NULL DEFAULT ((0)),
	[LGFHBV_PRIX_TTC] [money] NULL DEFAULT ((0)),
	[LGFHBV_BGRATUIT] [bit] NULL DEFAULT ((0)),
	[LGFHBV_ETAT] [int] NULL DEFAULT ((0)),

 CONSTRAINT [LIGNE_FACTHBV$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[LGFHBV_ID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE COMMANDE
	ADD CMD_IDFHBV int null
GO
ALTER TABLE COMMANDE
	ADD CMD_ORIGINE nvarchar(10)
GO

UPDATE COMMANDE SET CMD_ORIGINE = 'VINICOM' WHERE CMD_ORIGINE = ''
GO

ALTER TABLE CLIENT
	ADD CLT_ORIGINE nvarchar(10)
GO

-- Procédure de récupération du prochain numéro de facture HOBIVIN
ALTER TABLE dbo.CONSTANTES ADD
	CST_DERN_NUM_FACT_HBV int NULL
GO
ALTER TABLE dbo.CONSTANTES ADD CONSTRAINT
	DF_CONSTANTES_CST_DERN_NUM_FACT_HBV DEFAULT 1 FOR CST_DERN_NUM_FACT_HBV
GO
CREATE PROCEDURE [dbo].[GETNEXTNUM_FACTHBV]	 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON
	DECLARE @C1 as int

BEGIN TRANSACTION T1
	-- Lecture du Numéro
	SELECT @C1 = CST_DERN_NUM_FACT_HBV FROM CONSTANTES
    -- Mise à jout de la base
	UPDATE CONSTANTES SET CST_DERN_NUM_FACT_HBV = (@C1+1)
    -- Retour de la valeur
	SELECT @C1 as CODE 
COMMIT TRANSACTION T1

END

GO
-- Recopie des infos d'export vers quadra depuis les information de transport
insert into EXPORTPARAM (EXP_TYPE,EXP_NLIGNE, EXP_NCHAMPS, EXP_TYPECHAMPS, EXP_VALEUR, EXP_LONGUEUR, EXP_DESCRIPTION)
SELECT        'HBV',EXP_NLIGNE, EXP_NCHAMPS, EXP_TYPECHAMPS, EXP_VALEUR, EXP_LONGUEUR, EXP_DESCRIPTION
FROM            EXPORTPARAM
WHERE        (EXP_TYPE = N'TRP')


--   MISE A JOUR DE L'INDICATEUR
UPDATE CONSTANTES SET CST_VERSION_BD = '5.9'
GO
