USE [vnc5]
GO

/****** Object:  View [dbo].[CAFOURNISSEUR2]    Script Date: 09/06/2017 10:01:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[CAFOURNISSEUR2]
AS
SELECT        CMD1.CMD_DATE, F1.FRN_CODE, F1.FRN_NOM, P1.PRD_CODE, P1.PRD_LIBELLE, LG1.LGCM_PRIX_HT as CA_HT, LG1.LGCM_QTE_COMMANDE As QTE,dbo.CONTENANT.CONT_BOUT, CMD1.CMD_ORIGINE
FROM            dbo.FOURNISSEUR AS F1 INNER JOIN
                         dbo.COMMANDE AS CMD1 INNER JOIN
                         dbo.PRODUIT AS P1 INNER JOIN
                         dbo.LIGNE_COMMANDE AS LG1 ON P1.PRD_ID = LG1.LGCM_PRD_ID INNER JOIN
                         dbo.CONTENANT ON P1.PRD_CONT_ID = dbo.CONTENANT.CONT_ID ON CMD1.CMD_ID = LG1.LGCM_CMD_ID ON F1.FRN_ID = P1.PRD_FRN_ID
WHERE        (YEAR(CMD1.CMD_DATE) >= YEAR(GETDATE()) - 3)


GO


