SELECT        CLIENT.CLT_IDPRESTASHOP, PRODUIT.PRD_CODE, PRECOMMANDE.PCMD_QTE_HAB, PRECOMMANDE.PCMD_PRIXU
FROM            CLIENT INNER JOIN
                         PRECOMMANDE ON CLIENT.CLT_ID = PRECOMMANDE.PCMD_CLT_ID INNER JOIN
                         PRODUIT ON PRECOMMANDE.PCMD_PRD_ID = PRODUIT.PRD_ID
WHERE CLT_IDPRESTASHOP IS NOT NULL AND CLT_IDPRESTASHOP >0
ORDER BY CLT_IDPRESTASHOP
